# Day 10 – Flight Operations Data Analysis

## Complete Pandas Data Analysis Workflow

This notebook follows the complete workflow covered in the Day 10 notes:

**Raw Data → Ingest → Clean → Transform → Analyze → Export**

The provided Flight Operations dataset is loaded with Pandas and analyzed through inspection, cleaning, transformations, selection/filtering, sorting, grouping, aggregation, and key findings.

### Questions addressed
1. What is the overall scale and structure of the flight dataset?
2. How are flights distributed by airline and status?
3. Which airlines generate the most estimated revenue?
4. Which travel classes contribute most passengers and revenue?
5. How do weather conditions relate to delays and satisfaction?
6. Which routes have the highest estimated revenue?
7. Which booking channels contribute the most revenue and satisfaction?
8. What are the main operational findings from the dataset?

In [1]:
import pandas as pd
from io import StringIO

# The provided Flight Operations CSV is embedded so this notebook is
# self-contained and can be run without a separate file upload.
csv_data = 'Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction\nFL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3\nFL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5\nFL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2\nFL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2\nFL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5\nFL0006,2026-05-20,Akasa Air,Kochi,Delhi,Airbus A319,Economy,123,220,5636,35.0,Delayed,Cloudy,Travel Agency,13,Vegetarian,2\nFL0007,2026-06-17,Air India Express,Delhi,Srinagar,Airbus A319,Premium Economy,178,210,9430,0.0,On Time,Storm,Online Travel Portal,18,Vegetarian,4\nFL0008,2026-04-28,Air India,Delhi,Chennai,Airbus A319,Business,157,220,14173,0.0,On Time,Fog,Airline Website,25,Vegan,5\nFL0009,2026-01-25,Akasa Air,Delhi,Chennai,Airbus A320,Economy,82,210,5893,75.0,Delayed,Cloudy,Mobile App,8,Vegetarian,4\nFL0010,2026-06-12,Akasa Air,Ahmedabad,Bengaluru,Airbus A321,Economy,125,220,2500,12.0,On Time,Cloudy,Online Travel Portal,23,Non-Vegetarian,4\nFL0011,2026-04-17,Air India,Mumbai,Bengaluru,Airbus A321,Economy,195,189,3393,5.0,On Time,Clear,Airline Website,17,Vegetarian,2\nFL0012,2026-03-30,Akasa Air,Lucknow,Delhi,Boeing 737,Economy,51,220,3046,5.0,On Time,Clear,Online Travel Portal,19,Non-Vegetarian,3\nFL0013,2026-05-14,SpiceJet,Pune,Delhi,Airbus A319,Economy,162,220,4689,0.0,On Time,Cloudy,Mobile App,6,Vegetarian,5\nFL0014,2026-06-14,Air India,Lucknow,Delhi,Airbus A321,Economy,78,220,2744,0.0,On Time,Cloudy,Online Travel Portal,13,No Meal,5\nFL0015,2026-01-21,Akasa Air,Lucknow,Delhi,Boeing 737,Economy,133,186,3911,0.0,On Time,Cloudy,Travel Agency,21,No Meal,5\nFL0016,2026-05-15,Akasa Air,Mumbai,Bengaluru,Boeing 737,Premium Economy,69,186,7860,0.0,On Time,Storm,Mobile App,5,Vegan,3\nFL0017,2026-05-24,SpiceJet,Delhi,Chennai,Airbus A321,Economy,73,220,4256,20.0,Delayed,Rain,Travel Agency,22,Non-Vegetarian,2\nFL0018,2026-03-09,Air India Express,Jaipur,Mumbai,Airbus A321,Economy,88,180,6133,20.0,Delayed,Clear,Travel Agency,13,Vegetarian,4\nFL0019,2026-03-22,Vistara,Bengaluru,Kochi,Airbus A319,Economy,61,180,4986,0.0,On Time,Clear,Airline Website,8,Non-Vegetarian,2\nFL0020,2026-02-01,SpiceJet,Mumbai,Kolkata,Airbus A320,Economy,125,210,5715,12.0,On Time,Fog,Travel Agency,24,Non-Vegetarian,5\nFL0021,2026-06-23,Vistara,Srinagar,Delhi,Airbus A320,Premium Economy,173,189,9018,0.0,On Time,Fog,Airline Website,14,Vegan,4\nFL0022,2026-02-01,Vistara,Kochi,Delhi,Airbus A321,Economy,126,220,5887,75.0,Delayed,Clear,Airline Website,10,Vegetarian,2\nFL0023,2026-02-02,Akasa Air,Delhi,Mumbai,Airbus A319,Economy,52,210,4620,12.0,On Time,Fog,Mobile App,9,Non-Vegetarian,2\nFL0024,2026-05-19,SpiceJet,Ahmedabad,Bengaluru,Airbus A319,Economy,110,186,5578,,Cancelled,Rain,Travel Agency,9,Vegetarian,3\nFL0025,2026-01-10,Vistara,Chennai,Mumbai,Airbus A320,Economy,112,189,6784,12.0,On Time,Clear,Mobile App,20,Vegetarian,3\nFL0026,2026-05-11,Air India,Ahmedabad,Bengaluru,Boeing 737,Premium Economy,137,186,8836,12.0,On Time,Fog,Online Travel Portal,22,No Meal,4\nFL0027,2026-02-10,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Economy,169,180,3973,110.0,Delayed,Clear,Mobile App,7,Vegan,4\nFL0028,2026-03-09,SpiceJet,Chennai,Mumbai,Boeing 737,Economy,49,220,3311,0.0,On Time,Clear,Online Travel Portal,17,Non-Vegetarian,2\nFL0029,2026-02-06,Air India Express,Mumbai,Bengaluru,Airbus A321,Premium Economy,185,189,8098,0.0,On Time,Rain,Travel Agency,22,Vegan,4\nFL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3\nFL0031,2026-01-08,Vistara,Delhi,Srinagar,Airbus A321,Premium Economy,209,180,9962,50.0,Delayed,Cloudy,Mobile App,9,Vegetarian,4\nFL0032,2026-01-28,Vistara,Hyderabad,Kolkata,Airbus A319,Premium Economy,142,189,6730,12.0,On Time,Fog,Airline Website,22,Non-Vegetarian,4\nFL0033,2026-04-27,Akasa Air,Ahmedabad,Bengaluru,Boeing 737,Business,66,180,17625,35.0,Delayed,Cloudy,Mobile App,15,No Meal,4\nFL0034,2026-06-18,Air India Express,Delhi,Chennai,Boeing 737,Premium Economy,125,186,9278,0.0,On Time,Rain,Online Travel Portal,23,No Meal,3\nFL0035,2026-04-24,Vistara,Delhi,Srinagar,Boeing 737,Premium Economy,77,210,11441,0.0,On Time,Fog,Travel Agency,9,Vegan,3\nFL0036,2026-02-06,Akasa Air,Delhi,Chennai,Airbus A320,Economy,113,189,3471,12.0,On Time,Rain,Online Travel Portal,15,Vegetarian,5\nFL0037,2026-06-23,Vistara,Bengaluru,Kochi,Airbus A320,Premium Economy,184,220,11614,0.0,On Time,Fog,Mobile App,5,Vegan,4\nFL0038,2026-03-27,Air India,Delhi,Srinagar,Airbus A320,Economy,166,210,5972,,Cancelled,Rain,Travel Agency,5,Non-Vegetarian,5\nFL0039,2026-03-12,IndiGo,Chennai,Mumbai,Airbus A320,Economy,65,220,5085,20.0,Delayed,Rain,Mobile App,19,Non-Vegetarian,3\nFL0040,2026-03-21,Vistara,Kochi,Delhi,Airbus A319,Economy,178,220,5361,12.0,On Time,Cloudy,Mobile App,20,Vegan,4\nFL0041,2026-03-23,Akasa Air,Delhi,Chennai,Airbus A321,Economy,170,189,4013,,Cancelled,Fog,Travel Agency,13,No Meal,3\nFL0042,2026-03-12,IndiGo,Delhi,Chennai,Boeing 737,Economy,122,186,5670,12.0,On Time,Storm,Airline Website,21,Vegan,5\nFL0043,2026-06-19,Vistara,Delhi,Chennai,Airbus A319,Economy,64,220,4029,50.0,Delayed,Clear,Mobile App,5,No Meal,3\nFL0044,2026-04-20,Air India Express,Bengaluru,Hyderabad,Airbus A319,Economy,176,186,3075,35.0,Delayed,Storm,Travel Agency,16,No Meal,3\nFL0045,2026-06-05,SpiceJet,Delhi,Srinagar,Airbus A320,Economy,81,186,3975,35.0,Delayed,Clear,Travel Agency,14,Non-Vegetarian,3\nFL0046,2026-05-19,Air India,Mumbai,Kolkata,Airbus A321,Economy,162,186,3371,0.0,On Time,Storm,Online Travel Portal,22,Vegetarian,4\nFL0047,2026-05-12,Air India Express,Bengaluru,Hyderabad,Airbus A320,Economy,164,210,3135,0.0,On Time,Clear,Airline Website,8,Vegan,4\nFL0048,2026-01-08,Air India,Delhi,Chennai,Airbus A321,Economy,68,210,3697,20.0,Delayed,Fog,Mobile App,16,Non-Vegetarian,5\nFL0049,2026-04-19,SpiceJet,Kochi,Delhi,Airbus A319,Economy,98,189,4968,12.0,On Time,Cloudy,Mobile App,8,Vegetarian,4\nFL0050,2026-06-23,Akasa Air,Kochi,Delhi,Airbus A320,Economy,74,186,3754,0.0,On Time,Cloudy,Travel Agency,14,Vegan,5\nFL0051,2026-05-03,Air India,Delhi,Mumbai,Airbus A321,Economy,135,210,5129,110.0,Delayed,Rain,Online Travel Portal,17,Vegetarian,4\nFL0052,2026-03-07,SpiceJet,Jaipur,Mumbai,Airbus A320,Business,163,210,13824,0.0,On Time,Rain,Travel Agency,6,Vegetarian,2\nFL0053,2026-05-16,Akasa Air,Mumbai,Bengaluru,Airbus A319,Business,72,210,21499,35.0,Delayed,Clear,Mobile App,15,Non-Vegetarian,2\nFL0054,2026-04-11,SpiceJet,Mumbai,Bengaluru,Airbus A320,Economy,49,180,4738,20.0,Delayed,Rain,Mobile App,14,No Meal,3\nFL0055,2026-04-30,IndiGo,Delhi,Chennai,Airbus A319,Economy,106,220,5432,50.0,Delayed,Storm,Mobile App,19,Non-Vegetarian,2\nFL0056,2026-05-02,Air India Express,Pune,Delhi,Airbus A320,Economy,180,180,6397,5.0,On Time,Fog,Mobile App,14,Non-Vegetarian,4\nFL0057,2026-04-21,SpiceJet,Mumbai,Kolkata,Airbus A320,Premium Economy,51,189,10530,12.0,On Time,Rain,Mobile App,23,Vegetarian,3\nFL0058,2026-04-14,IndiGo,Hyderabad,Kolkata,Boeing 737,Premium Economy,151,210,6834,110.0,Delayed,Cloudy,Travel Agency,16,Vegetarian,4\nFL0059,2026-01-10,Air India Express,Delhi,Srinagar,Airbus A319,Economy,159,220,3708,20.0,Delayed,Storm,Airline Website,11,No Meal,2\nFL0060,2026-01-24,IndiGo,Mumbai,Kolkata,Airbus A319,Economy,116,186,3382,0.0,On Time,Rain,Airline Website,22,Non-Vegetarian,3\nFL0061,2026-01-14,IndiGo,Hyderabad,Kolkata,Airbus A319,Economy,182,210,4165,5.0,On Time,Storm,Airline Website,19,Non-Vegetarian,3\nFL0062,2026-02-12,Air India,Bengaluru,Hyderabad,Airbus A319,Economy,131,210,6129,0.0,On Time,Clear,Travel Agency,7,Non-Vegetarian,3\nFL0063,2026-05-02,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,127,186,6511,5.0,On Time,Fog,Online Travel Portal,23,Vegan,4\nFL0064,2026-06-24,Vistara,Mumbai,Bengaluru,Airbus A321,Economy,105,180,4280,0.0,On Time,Storm,Airline Website,5,Vegan,3\nFL0065,2026-04-28,Air India Express,Kochi,Delhi,Airbus A319,Economy,165,186,4002,12.0,On Time,Clear,Mobile App,5,Vegan,3\nFL0066,2026-03-06,SpiceJet,Srinagar,Delhi,Airbus A320,Economy,83,210,4418,,Cancelled,Cloudy,Travel Agency,19,Vegetarian,5\nFL0067,2026-04-23,Vistara,Mumbai,Kolkata,Boeing 737,Premium Economy,109,210,8473,20.0,Delayed,Cloudy,Airline Website,24,Vegetarian,3\nFL0068,2026-06-28,Akasa Air,Bengaluru,Hyderabad,Airbus A321,Economy,102,189,5819,0.0,On Time,Rain,Online Travel Portal,11,Vegan,5\nFL0069,2026-03-09,SpiceJet,Kochi,Delhi,Airbus A321,Economy,107,186,5911,,Cancelled,Cloudy,Online Travel Portal,23,Non-Vegetarian,5\nFL0070,2026-06-12,SpiceJet,Srinagar,Delhi,Boeing 737,Economy,201,189,2959,20.0,Delayed,Rain,Online Travel Portal,12,Vegan,4\nFL0071,2026-03-31,SpiceJet,Lucknow,Delhi,Boeing 737,Premium Economy,101,180,10380,5.0,On Time,Cloudy,Online Travel Portal,16,Vegetarian,2\nFL0072,2026-02-25,IndiGo,Bengaluru,Hyderabad,Airbus A320,Economy,166,186,5227,5.0,On Time,Clear,Mobile App,17,Vegetarian,5\nFL0073,2026-03-30,IndiGo,Pune,Delhi,Airbus A320,Economy,151,186,3486,0.0,On Time,Rain,Mobile App,19,No Meal,2\nFL0074,2026-01-28,IndiGo,Ahmedabad,Bengaluru,Boeing 737,Premium Economy,186,210,7004,0.0,On Time,Cloudy,Online Travel Portal,19,Vegetarian,5\nFL0075,2026-02-03,Akasa Air,Jaipur,Mumbai,Boeing 737,Economy,153,180,6464,5.0,On Time,Clear,Airline Website,18,Non-Vegetarian,5\nFL0076,2026-01-18,IndiGo,Ahmedabad,Bengaluru,Airbus A321,Economy,108,210,6808,0.0,On Time,Storm,Travel Agency,13,No Meal,2\nFL0077,2026-02-27,Vistara,Kochi,Delhi,Airbus A319,Economy,150,180,3399,12.0,On Time,Storm,Travel Agency,12,Non-Vegetarian,5\nFL0078,2026-01-09,Vistara,Mumbai,Kolkata,Airbus A321,Economy,179,210,4686,0.0,On Time,Storm,Online Travel Portal,10,Vegan,4\nFL0079,2026-03-21,Vistara,Mumbai,Kolkata,Airbus A320,Economy,45,186,4597,12.0,On Time,Rain,Online Travel Portal,25,No Meal,5\nFL0080,2026-04-07,Vistara,Pune,Delhi,Airbus A320,Economy,155,210,5730,12.0,On Time,Rain,Online Travel Portal,16,Vegan,5\nFL0081,2026-04-03,SpiceJet,Delhi,Mumbai,Airbus A320,Economy,199,180,2378,50.0,Delayed,Rain,Online Travel Portal,13,No Meal,4\nFL0082,2026-03-07,Vistara,Bengaluru,Kochi,Airbus A319,Economy,59,180,3793,0.0,On Time,Storm,Airline Website,14,Non-Vegetarian,2\nFL0083,2026-04-18,Air India Express,Lucknow,Delhi,Airbus A319,Economy,71,180,2484,110.0,Delayed,Cloudy,Online Travel Portal,22,Vegetarian,4\nFL0084,2026-04-05,Air India Express,Srinagar,Delhi,Airbus A321,Economy,93,180,6135,0.0,On Time,Fog,Airline Website,7,No Meal,5\nFL0085,2026-05-03,Air India,Lucknow,Delhi,Airbus A319,Economy,45,189,3299,35.0,Delayed,Rain,Online Travel Portal,21,Non-Vegetarian,3\nFL0086,2026-02-10,Vistara,Delhi,Chennai,Airbus A319,Premium Economy,52,180,8607,0.0,On Time,Clear,Airline Website,16,Vegetarian,4\nFL0087,2026-02-26,SpiceJet,Chennai,Mumbai,Airbus A320,Economy,68,189,4704,5.0,On Time,Cloudy,Online Travel Portal,22,Vegan,3\nFL0088,2026-02-08,Vistara,Delhi,Srinagar,Airbus A321,Economy,75,210,4156,0.0,On Time,Cloudy,Travel Agency,20,Vegetarian,3\nFL0089,2026-03-15,Air India Express,Pune,Delhi,Boeing 737,Premium Economy,57,220,10062,0.0,On Time,Clear,Travel Agency,9,Vegan,5\nFL0090,2026-01-27,Vistara,Srinagar,Delhi,Airbus A321,Economy,111,210,3906,0.0,On Time,Clear,Airline Website,14,No Meal,2\nFL0091,2026-02-21,Vistara,Bengaluru,Kochi,Airbus A320,Economy,52,189,2251,0.0,On Time,Fog,Online Travel Portal,15,Non-Vegetarian,2\nFL0092,2026-06-23,Vistara,Delhi,Chennai,Airbus A321,Economy,170,210,6486,0.0,On Time,Rain,Travel Agency,17,Vegetarian,2\nFL0093,2026-04-30,Air India Express,Srinagar,Delhi,Airbus A319,Business,209,220,12970,0.0,On Time,Clear,Travel Agency,8,Vegan,2\nFL0094,2026-04-19,IndiGo,Bengaluru,Hyderabad,Airbus A320,Economy,116,186,4357,5.0,On Time,Storm,Online Travel Portal,16,Non-Vegetarian,5\nFL0095,2026-06-14,Vistara,Bengaluru,Kochi,Airbus A319,Economy,199,189,4369,0.0,On Time,Fog,Online Travel Portal,11,Vegetarian,5\nFL0096,2026-04-05,Akasa Air,Srinagar,Delhi,Boeing 737,Premium Economy,184,220,10970,12.0,On Time,Rain,Mobile App,15,Vegetarian,3\nFL0097,2026-03-10,Vistara,Kochi,Delhi,Airbus A319,Economy,90,186,6145,20.0,Delayed,Fog,Airline Website,13,Vegan,2\nFL0098,2026-01-12,SpiceJet,Ahmedabad,Bengaluru,Airbus A319,Economy,131,180,6466,35.0,Delayed,Rain,Online Travel Portal,7,Vegetarian,4\nFL0099,2026-01-15,Air India,Mumbai,Bengaluru,Boeing 737,Economy,108,189,3588,35.0,Delayed,Rain,Airline Website,14,Non-Vegetarian,4\nFL0100,2026-05-04,Akasa Air,Jaipur,Mumbai,Airbus A320,Economy,64,220,6324,0.0,On Time,Fog,Airline Website,24,Vegan,5\nFL0101,2026-05-24,IndiGo,Jaipur,Mumbai,Boeing 737,Economy,62,180,2552,50.0,Delayed,Cloudy,Airline Website,5,No Meal,2\nFL0102,2026-01-05,Air India,Jaipur,Mumbai,Airbus A319,Economy,158,180,2991,0.0,On Time,Cloudy,Airline Website,16,No Meal,2\nFL0103,2026-01-10,IndiGo,Bengaluru,Hyderabad,Airbus A319,Economy,167,210,7014,20.0,Delayed,Fog,Airline Website,8,Vegan,5\nFL0104,2026-04-02,IndiGo,Bengaluru,Hyderabad,Airbus A320,Economy,92,180,2811,0.0,On Time,Rain,Airline Website,25,Non-Vegetarian,2\nFL0105,2026-03-21,Vistara,Delhi,Mumbai,Boeing 737,Economy,158,180,3694,50.0,Delayed,Storm,Mobile App,6,Vegetarian,3\nFL0106,2026-04-23,IndiGo,Srinagar,Delhi,Boeing 737,Economy,83,220,3471,50.0,Delayed,Fog,Mobile App,23,Non-Vegetarian,3\nFL0107,2026-05-11,Akasa Air,Pune,Delhi,Airbus A320,Economy,95,210,3982,0.0,On Time,Fog,Airline Website,16,Vegetarian,3\nFL0108,2026-05-30,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,198,180,10551,75.0,Delayed,Rain,Travel Agency,13,Vegan,2\nFL0109,2026-04-12,SpiceJet,Srinagar,Delhi,Airbus A321,Business,129,180,16390,0.0,On Time,Rain,Online Travel Portal,11,Vegan,2\nFL0110,2026-03-10,Akasa Air,Delhi,Srinagar,Airbus A319,Economy,141,189,4046,0.0,On Time,Cloudy,Mobile App,23,Vegetarian,3\nFL0111,2026-05-16,Vistara,Delhi,Mumbai,Airbus A321,Premium Economy,124,186,6711,,Cancelled,Cloudy,Mobile App,19,Vegetarian,4\nFL0112,2026-04-08,IndiGo,Delhi,Mumbai,Boeing 737,Economy,183,220,3008,12.0,On Time,Rain,Airline Website,19,Vegetarian,2\nFL0113,2026-03-01,Air India Express,Bengaluru,Hyderabad,Airbus A319,Premium Economy,132,186,7119,0.0,On Time,Cloudy,Online Travel Portal,21,Non-Vegetarian,5\nFL0114,2026-06-27,Air India Express,Srinagar,Delhi,Airbus A320,Economy,79,180,6268,20.0,Delayed,Clear,Mobile App,21,Vegan,5\nFL0115,2026-04-27,Air India Express,Delhi,Mumbai,Airbus A319,Economy,77,186,3878,12.0,On Time,Rain,Mobile App,13,Non-Vegetarian,3\nFL0116,2026-03-17,Air India Express,Hyderabad,Kolkata,Boeing 737,Premium Economy,127,180,7931,0.0,On Time,Clear,Airline Website,18,Non-Vegetarian,5\nFL0117,2026-05-02,IndiGo,Mumbai,Bengaluru,Airbus A319,Economy,88,189,3261,0.0,On Time,Storm,Travel Agency,6,No Meal,2\nFL0118,2026-01-27,Air India Express,Jaipur,Mumbai,Airbus A320,Economy,72,210,3831,0.0,On Time,Cloudy,Travel Agency,5,Non-Vegetarian,2\nFL0119,2026-02-10,Air India Express,Delhi,Chennai,Boeing 737,Economy,66,189,3705,5.0,On Time,Clear,Mobile App,14,Vegetarian,2\nFL0120,2026-05-16,Air India,Lucknow,Delhi,Boeing 737,Economy,175,210,4472,20.0,Delayed,Cloudy,Airline Website,9,Non-Vegetarian,3\nFL0121,2026-06-29,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Premium Economy,141,186,9974,5.0,On Time,Fog,Airline Website,14,Vegetarian,4\nFL0122,2026-02-13,Air India,Mumbai,Kolkata,Airbus A319,Economy,178,189,5514,0.0,On Time,Rain,Airline Website,25,Non-Vegetarian,5\nFL0123,2026-03-07,Air India Express,Mumbai,Kolkata,Airbus A319,Premium Economy,148,210,8932,0.0,On Time,Cloudy,Mobile App,17,Vegetarian,4\nFL0124,2026-01-06,Vistara,Delhi,Chennai,Airbus A319,Economy,138,210,5399,0.0,On Time,Cloudy,Mobile App,11,No Meal,3\nFL0125,2026-05-20,Akasa Air,Srinagar,Delhi,Boeing 737,Premium Economy,72,180,9266,12.0,On Time,Rain,Online Travel Portal,24,Vegan,2\nFL0126,2026-03-04,Air India,Bengaluru,Kochi,Airbus A319,Economy,125,210,2516,5.0,On Time,Clear,Online Travel Portal,15,No Meal,5\nFL0127,2026-01-21,IndiGo,Delhi,Chennai,Airbus A321,Economy,184,180,4960,5.0,On Time,Fog,Mobile App,10,Vegetarian,5\nFL0128,2026-05-27,SpiceJet,Srinagar,Delhi,Airbus A319,Economy,67,180,6394,0.0,On Time,Clear,Airline Website,10,Non-Vegetarian,3\nFL0129,2026-01-04,SpiceJet,Lucknow,Delhi,Boeing 737,Premium Economy,67,210,5657,110.0,Delayed,Cloudy,Online Travel Portal,21,Non-Vegetarian,2\nFL0130,2026-04-08,Akasa Air,Kochi,Delhi,Boeing 737,Premium Economy,115,189,6890,0.0,On Time,Fog,Travel Agency,11,Non-Vegetarian,3\nFL0131,2026-04-21,Air India Express,Mumbai,Bengaluru,Boeing 737,Economy,159,220,6354,0.0,On Time,Cloudy,Travel Agency,14,No Meal,5\nFL0132,2026-02-04,Air India,Hyderabad,Kolkata,Airbus A321,Economy,61,220,3483,75.0,Delayed,Clear,Mobile App,18,No Meal,5\nFL0133,2026-02-10,IndiGo,Pune,Delhi,Airbus A321,Business,164,180,15324,0.0,On Time,Storm,Travel Agency,20,Vegetarian,4\nFL0134,2026-01-08,IndiGo,Ahmedabad,Bengaluru,Airbus A319,Premium Economy,77,220,10989,0.0,On Time,Cloudy,Travel Agency,17,Vegan,5\nFL0135,2026-05-09,Akasa Air,Pune,Delhi,Airbus A320,Economy,169,210,3422,0.0,On Time,Fog,Travel Agency,15,Vegetarian,2\nFL0136,2026-03-16,Vistara,Mumbai,Bengaluru,Boeing 737,Economy,150,180,4587,35.0,Delayed,Clear,Airline Website,19,Vegan,4\nFL0137,2026-03-14,Vistara,Mumbai,Bengaluru,Airbus A319,Economy,73,186,1949,35.0,Delayed,Rain,Airline Website,22,Non-Vegetarian,5\nFL0138,2026-01-19,Air India Express,Chennai,Mumbai,Boeing 737,Economy,61,180,6077,0.0,On Time,Rain,Travel Agency,14,No Meal,2\nFL0139,2026-01-27,Air India Express,Delhi,Chennai,Airbus A321,Business,169,189,27832,20.0,Delayed,Clear,Airline Website,10,Vegan,4\nFL0140,2026-01-10,Air India Express,Pune,Delhi,Airbus A320,Premium Economy,87,180,10489,12.0,On Time,Storm,Travel Agency,12,Vegetarian,4\nFL0141,2026-02-26,SpiceJet,Delhi,Srinagar,Boeing 737,Economy,100,210,4660,12.0,On Time,Clear,Online Travel Portal,21,Vegan,4\nFL0142,2026-03-10,SpiceJet,Delhi,Srinagar,Airbus A320,Economy,175,180,4825,0.0,On Time,Fog,Travel Agency,16,Vegan,5\nFL0143,2026-02-05,IndiGo,Kochi,Delhi,Airbus A319,Premium Economy,181,189,7406,0.0,On Time,Cloudy,Travel Agency,5,Vegan,5\nFL0144,2026-02-25,Akasa Air,Mumbai,Bengaluru,Airbus A319,Economy,50,210,5522,12.0,On Time,Storm,Airline Website,25,Vegan,3\nFL0145,2026-01-20,Akasa Air,Bengaluru,Hyderabad,Airbus A319,Economy,114,186,3022,20.0,Delayed,Fog,Mobile App,22,No Meal,2\nFL0146,2026-01-03,Air India,Chennai,Mumbai,Boeing 737,Economy,64,220,4171,5.0,On Time,Fog,Travel Agency,18,Non-Vegetarian,2\nFL0147,2026-02-18,IndiGo,Mumbai,Kolkata,Airbus A319,Premium Economy,115,210,9106,110.0,Delayed,Rain,Online Travel Portal,19,Vegetarian,5\nFL0148,2026-06-26,IndiGo,Delhi,Srinagar,Airbus A321,Economy,147,189,5589,0.0,On Time,Rain,Travel Agency,9,Vegan,2\nFL0149,2026-02-10,Akasa Air,Jaipur,Mumbai,Airbus A319,Economy,202,210,6239,5.0,On Time,Rain,Online Travel Portal,8,No Meal,5\nFL0150,2026-06-15,Vistara,Chennai,Mumbai,Boeing 737,Economy,131,210,6572,5.0,On Time,Storm,Mobile App,25,No Meal,5\nFL0151,2026-05-19,Air India,Delhi,Mumbai,Boeing 737,Economy,173,189,6741,0.0,On Time,Rain,Online Travel Portal,7,No Meal,5\nFL0152,2026-05-14,IndiGo,Mumbai,Kolkata,Airbus A320,Premium Economy,149,189,7412,0.0,On Time,Clear,Online Travel Portal,10,Non-Vegetarian,2\nFL0153,2026-03-25,Akasa Air,Bengaluru,Hyderabad,Boeing 737,Economy,125,220,2866,0.0,On Time,Rain,Travel Agency,20,Vegetarian,2\nFL0154,2026-04-09,Air India,Mumbai,Bengaluru,Airbus A321,Economy,201,186,3823,20.0,Delayed,Clear,Online Travel Portal,13,Vegan,2\nFL0155,2026-03-12,SpiceJet,Kochi,Delhi,Airbus A319,Economy,75,189,3070,12.0,On Time,Fog,Online Travel Portal,20,Vegan,5\nFL0156,2026-03-20,Vistara,Mumbai,Bengaluru,Boeing 737,Business,80,186,15040,0.0,On Time,Storm,Online Travel Portal,20,Vegetarian,3\nFL0157,2026-04-25,Akasa Air,Delhi,Srinagar,Boeing 737,Economy,120,186,2188,35.0,Delayed,Storm,Mobile App,14,Non-Vegetarian,2\nFL0158,2026-02-24,Vistara,Mumbai,Kolkata,Boeing 737,Economy,176,186,3479,75.0,Delayed,Fog,Travel Agency,14,Vegetarian,4\nFL0159,2026-04-08,IndiGo,Chennai,Mumbai,Boeing 737,Economy,64,186,6411,0.0,On Time,Cloudy,Online Travel Portal,16,Vegetarian,2\nFL0160,2026-06-23,Vistara,Lucknow,Delhi,Airbus A321,Economy,91,210,5443,75.0,Delayed,Storm,Airline Website,10,No Meal,2\nFL0161,2026-04-03,Vistara,Delhi,Mumbai,Airbus A320,Economy,135,220,6154,,Cancelled,Storm,Mobile App,6,Vegetarian,2\nFL0162,2026-01-18,Air India,Hyderabad,Kolkata,Airbus A321,Economy,128,189,5263,110.0,Delayed,Rain,Mobile App,6,Non-Vegetarian,3\nFL0163,2026-03-29,SpiceJet,Srinagar,Delhi,Boeing 737,Economy,177,220,2385,5.0,On Time,Clear,Travel Agency,23,Vegetarian,5\nFL0164,2026-06-07,SpiceJet,Mumbai,Bengaluru,Airbus A321,Economy,139,189,6327,0.0,On Time,Rain,Travel Agency,20,Vegan,4\nFL0165,2026-03-31,Air India,Ahmedabad,Bengaluru,Airbus A320,Economy,137,220,4992,12.0,On Time,Clear,Mobile App,18,Vegetarian,3\nFL0166,2026-05-23,Akasa Air,Kochi,Delhi,Airbus A320,Economy,108,210,2314,0.0,On Time,Fog,Online Travel Portal,6,Vegan,2\nFL0167,2026-06-15,SpiceJet,Ahmedabad,Bengaluru,Airbus A321,Economy,148,180,6593,0.0,On Time,Rain,Online Travel Portal,15,Non-Vegetarian,5\nFL0168,2026-05-01,Air India,Delhi,Mumbai,Airbus A319,Economy,47,220,6479,0.0,On Time,Cloudy,Mobile App,18,Vegan,4\nFL0169,2026-02-10,IndiGo,Delhi,Chennai,Airbus A320,Economy,152,220,4051,35.0,Delayed,Clear,Online Travel Portal,10,No Meal,2\nFL0170,2026-06-25,IndiGo,Mumbai,Kolkata,Airbus A319,Economy,130,180,3938,110.0,Delayed,Rain,Online Travel Portal,17,No Meal,4\nFL0171,2026-02-09,SpiceJet,Ahmedabad,Bengaluru,Boeing 737,Business,138,220,12597,20.0,Delayed,Storm,Mobile App,21,Non-Vegetarian,3\nFL0172,2026-06-02,IndiGo,Pune,Delhi,Airbus A319,Premium Economy,166,180,9210,12.0,On Time,Fog,Airline Website,17,Vegetarian,2\nFL0173,2026-06-02,SpiceJet,Srinagar,Delhi,Airbus A319,Economy,143,189,6817,75.0,Delayed,Storm,Mobile App,20,No Meal,2\nFL0174,2026-04-27,Vistara,Hyderabad,Kolkata,Airbus A319,Economy,93,189,3392,50.0,Delayed,Fog,Airline Website,10,No Meal,3\nFL0175,2026-04-23,Akasa Air,Bengaluru,Kochi,Airbus A321,Economy,116,180,5883,0.0,On Time,Cloudy,Online Travel Portal,14,Non-Vegetarian,5\nFL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5\nFL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5\nFL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3\nFL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2\nFL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5\n'
df = pd.read_csv(StringIO(csv_data))

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (180, 17)

## 1. Inspect and Understand the Raw Dataset

In [2]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

print("Random sample:")
display(df.sample(5, random_state=42))

print("Columns:")
print(df.columns.tolist())

print("\nIndex:")
print(df.index)

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

print("\nDescriptive statistics:")
display(df.describe(include="all").transpose())

First 5 rows:

  Flight_ID Flight_Date  ... Meal_Preference Passenger_Satisfaction
0    FL0001  2026-03-23  ...         No Meal                      3
1    FL0002  2026-06-07  ...           Vegan                      5
2    FL0003  2026-05-12  ...         No Meal                      2
3    FL0004  2026-05-30  ...         No Meal                      2
4    FL0005  2026-02-27  ...         No Meal                      5

[5 rows x 17 columns]

Last 5 rows:

    Flight_ID Flight_Date  ... Meal_Preference Passenger_Satisfaction
175    FL0176  2026-04-10  ...      Vegetarian                      5
176    FL0177  2026-02-17  ...         No Meal                      5
177    FL0178  2026-04-30  ...      Vegetarian                      3
178    FL0179  2026-05-08  ...         No Meal                      2
179    FL0180  2026-01-22  ...         No Meal                      5

[5 rows x 17 columns]

Random sample:

    Flight_ID Flight_Date  ... Meal_Preference Passenger_Satisfaction
19     FL0020  2026-02-01  ...  Non-Vegetarian                      5
42     FL0043  2026-06-19  ...         No Meal                      3
153    FL0154  2026-04-09  ...           Vegan                      2
78     FL0079  2026-03-21  ...         No Meal                      5
145    FL0146  2026-01-03  ...  Non-Vegetarian                      2

[5 rows x 17 columns]

Columns:
['Flight_ID', 'Flight_Date', 'Airline', 'Origin', 'Destination', 'Aircraft', 'Travel_Class', 'Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Flight_Status', 'Weather', 'Booking_Channel', 'Avg_Baggage_Kg', 'Meal_Preference', 'Passenger_Satisfaction']

Index:
RangeIndex(start=0, stop=180, step=1)

Data types:
Flight_ID                  object
Flight_Date                object
Airline                    object
Origin                     object
Destination                object
Aircraft                   object
Travel_Class               object
Passengers                  int64
Seat_Capacity               int64
Average_Ticket_Price        int64
Delay_Minutes             float64
Flight_Status              object
Weather                    object
Booking_Channel            object
Avg_Baggage_Kg              int64
Meal_Preference            object
Passenger_Satisfaction      int64
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    object
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), object(11)
memory usage: 24.0+ KB

Descriptive statistics:

                        count unique  ...     75%      max
Flight_ID                 180    180  ...     NaN      NaN
Flight_Date               180    111  ...     NaN      NaN
Airline                   180      6  ...     NaN      NaN
Origin                    180     11  ...     NaN      NaN
Destination               180      8  ...     NaN      NaN
Aircraft                  180      4  ...     NaN      NaN
Travel_Class              180      3  ...     NaN      NaN
Passengers              180.0    NaN  ...  162.25    210.0
Seat_Capacity           180.0    NaN  ...   210.0    220.0
Average_Ticket_Price    180.0    NaN  ...  6790.0  27832.0
Delay_Minutes           173.0    NaN  ...    20.0    110.0
Flight_Status             180      3  ...     NaN      NaN
Weather                   180      5  ...     NaN      NaN
Booking_Channel           180      4  ...     NaN      NaN
Avg_Baggage_Kg          180.0    NaN  ...    20.0     25.0
Meal_Preference           180      4  ...     NaN      NaN
Passenger_Satisfaction  180.0    NaN  ...     5.0      5.0

[17 rows x 11 columns]

## 2. Check Data Quality

In [3]:
print("Missing values by column:")
display(df.isna().sum().sort_values(ascending=False))

print("Duplicate rows:", df.duplicated().sum())

print("Unique Flight IDs:", df["Flight_ID"].nunique())

Missing values by column:

Delay_Minutes             7
Flight_ID                 0
Flight_Date               0
Origin                    0
Airline                   0
Aircraft                  0
Travel_Class              0
Passengers                0
Destination               0
Seat_Capacity             0
Average_Ticket_Price      0
Flight_Status             0
Weather                   0
Booking_Channel           0
Avg_Baggage_Kg            0
Meal_Preference           0
Passenger_Satisfaction    0
dtype: int64

Duplicate rows: 0
Unique Flight IDs: 180

## 3. Clean the Dataset

Following the Day 10 workflow notes, cleaning includes missing values, incorrect data types, and invalid data. The notes specifically demonstrate converting dates with `pd.to_datetime()` and removing/filling missing values. fileciteturn3file0L2-L8

Here, `Flight_Date` is converted to datetime and the seven missing `Delay_Minutes` values are filled with the median delay so that delay-based analysis can use all 180 flights.

In [4]:
df["Flight_Date"] = pd.to_datetime(df["Flight_Date"])

missing_delay_before = df["Delay_Minutes"].isna().sum()
delay_median = df["Delay_Minutes"].median()

df["Delay_Minutes"] = df["Delay_Minutes"].fillna(delay_median)

print("Missing Delay_Minutes before cleaning:", missing_delay_before)
print("Median delay used for filling:", delay_median)
print("Missing Delay_Minutes after cleaning:", df["Delay_Minutes"].isna().sum())

Missing Delay_Minutes before cleaning: 7
Median delay used for filling: 5.0
Missing Delay_Minutes after cleaning: 0

## 4. Transform the Data

In [5]:
# Create useful derived columns.
df["Estimated_Revenue"] = df["Passengers"] * df["Average_Ticket_Price"]
df["Load_Factor_Pct"] = (df["Passengers"] / df["Seat_Capacity"]) * 100
df["Flight_Month"] = df["Flight_Date"].dt.month
df["Flight_Month_Name"] = df["Flight_Date"].dt.month_name()
df["Day_of_Week"] = df["Flight_Date"].dt.day_name()

display(df[
    ["Flight_ID", "Flight_Date", "Passengers", "Seat_Capacity",
     "Average_Ticket_Price", "Estimated_Revenue", "Load_Factor_Pct"]
].head(10))

  Flight_ID Flight_Date  ...  Estimated_Revenue  Load_Factor_Pct
0    FL0001  2026-03-23  ...            1447740       116.666667
1    FL0002  2026-06-07  ...             312760        33.333333
2    FL0003  2026-05-12  ...             315771        30.454545
3    FL0004  2026-05-30  ...             580023        69.545455
4    FL0005  2026-02-27  ...            1157890        98.888889
5    FL0006  2026-05-20  ...             693228        55.909091
6    FL0007  2026-06-17  ...            1678540        84.761905
7    FL0008  2026-04-28  ...            2225161        71.363636
8    FL0009  2026-01-25  ...             483226        39.047619
9    FL0010  2026-06-12  ...             312500        56.818182

[10 rows x 7 columns]

## 5. Dataset-Level Summary

In [6]:
total_flights = df["Flight_ID"].nunique()
total_passengers = df["Passengers"].sum()
total_capacity = df["Seat_Capacity"].sum()
overall_load_factor = total_passengers / total_capacity * 100
estimated_revenue = df["Estimated_Revenue"].sum()
average_ticket_price = df["Average_Ticket_Price"].mean()
average_delay = df["Delay_Minutes"].mean()
average_satisfaction = df["Passenger_Satisfaction"].mean()
delayed_rate = (df["Flight_Status"].eq("Delayed").mean()) * 100
cancelled_rate = (df["Flight_Status"].eq("Cancelled").mean()) * 100

summary = pd.Series({
    "Total flights": total_flights,
    "Total passengers": total_passengers,
    "Overall load factor (%)": overall_load_factor,
    "Estimated revenue": estimated_revenue,
    "Average ticket price": average_ticket_price,
    "Average delay (minutes)": average_delay,
    "Average passenger satisfaction": average_satisfaction,
    "Delayed flights (%)": delayed_rate,
    "Cancelled flights (%)": cancelled_rate
})

display(summary.to_frame("Value"))

                                       Value
Total flights                   1.800000e+02
Total passengers                2.209900e+04
Overall load factor (%)         6.224544e+01
Estimated revenue               1.376432e+08
Average ticket price            6.111678e+03
Average delay (minutes)         1.877778e+01
Average passenger satisfaction  3.494444e+00
Delayed flights (%)             3.277778e+01
Cancelled flights (%)           3.888889e+00

## 6. Selection and Filtering

In [7]:
# Select relevant columns.
display(df.loc[:, [
    "Flight_ID", "Airline", "Origin", "Destination",
    "Passengers", "Delay_Minutes", "Flight_Status"
]].head(10))

# Flights delayed by more than 30 minutes.
delayed_30 = df.loc[df["Delay_Minutes"] > 30]
print("Flights delayed by more than 30 minutes:", len(delayed_30))
display(delayed_30[
    ["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes"]
].head(15))

# High passenger-load flights.
high_load = df.loc[df["Load_Factor_Pct"] >= 80]
print("Flights with load factor >= 80%:", len(high_load))
display(high_load[
    ["Flight_ID", "Airline", "Passengers", "Seat_Capacity", "Load_Factor_Pct"]
].head(15))

# Delayed flights during adverse weather.
adverse_weather_delays = df.loc[
    (df["Flight_Status"] == "Delayed") &
    (df["Weather"].isin(["Rain", "Storm", "Fog"]))
]
print("Delayed flights in Rain/Storm/Fog:", len(adverse_weather_delays))

  Flight_ID            Airline  ... Delay_Minutes Flight_Status
0    FL0001           SpiceJet  ...          50.0       Delayed
1    FL0002          Akasa Air  ...           0.0       On Time
2    FL0003          Air India  ...           5.0       On Time
3    FL0004          Akasa Air  ...          35.0       Delayed
4    FL0005          Air India  ...          20.0       Delayed
5    FL0006          Akasa Air  ...          35.0       Delayed
6    FL0007  Air India Express  ...           0.0       On Time
7    FL0008          Air India  ...           0.0       On Time
8    FL0009          Akasa Air  ...          75.0       Delayed
9    FL0010          Akasa Air  ...          12.0       On Time

[10 rows x 7 columns]

Flights delayed by more than 30 minutes: 40

   Flight_ID            Airline     Origin Destination  Delay_Minutes
0     FL0001           SpiceJet     Mumbai   Bengaluru           50.0
3     FL0004          Akasa Air   Srinagar       Delhi           35.0
5     FL0006          Akasa Air      Kochi       Delhi           35.0
8     FL0009          Akasa Air      Delhi     Chennai           75.0
21    FL0022            Vistara      Kochi       Delhi           75.0
26    FL0027           SpiceJet  Bengaluru   Hyderabad          110.0
29    FL0030           SpiceJet      Delhi    Srinagar           75.0
30    FL0031            Vistara      Delhi    Srinagar           50.0
32    FL0033          Akasa Air  Ahmedabad   Bengaluru           35.0
42    FL0043            Vistara      Delhi     Chennai           50.0
43    FL0044  Air India Express  Bengaluru   Hyderabad           35.0
44    FL0045           SpiceJet      Delhi    Srinagar           35.0
50    FL0051          Air India      Delhi      Mumbai          110.0
52    FL0053          Akasa Air     Mumbai   Bengaluru           35.0
54    FL0055             IndiGo      Delhi     Chennai           50.0

Flights with load factor >= 80%: 49

   Flight_ID            Airline  Passengers  Seat_Capacity  Load_Factor_Pct
0     FL0001           SpiceJet         210            180       116.666667
4     FL0005          Air India         178            180        98.888889
6     FL0007  Air India Express         178            210        84.761905
10    FL0011          Air India         195            189       103.174603
20    FL0021            Vistara         173            189        91.534392
26    FL0027           SpiceJet         169            180        93.888889
28    FL0029  Air India Express         185            189        97.883598
29    FL0030           SpiceJet         200            210        95.238095
30    FL0031            Vistara         209            180       116.111111
36    FL0037            Vistara         184            220        83.636364
39    FL0040            Vistara         178            220        80.909091
40    FL0041          Akasa Air         170            189        89.947090
43    FL0044  Air India Express         176            186        94.623656
45    FL0046          Air India         162            186        87.096774
55    FL0056  Air India Express         180            180       100.000000

Delayed flights in Rain/Storm/Fog: 35

## 7. Sorting

In [8]:
# Top flights by estimated revenue.
top_revenue_flights = df.sort_values(
    "Estimated_Revenue", ascending=False
)
display(top_revenue_flights[
    ["Flight_ID", "Airline", "Travel_Class", "Passengers",
     "Average_Ticket_Price", "Estimated_Revenue"]
].head(10))

# Flights with the longest delays.
top_delays = df.sort_values(
    "Delay_Minutes", ascending=False
)
display(top_delays[
    ["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes"]
].head(10))

    Flight_ID            Airline  ... Average_Ticket_Price  Estimated_Revenue
138    FL0139  Air India Express  ...                27832            4703608
92     FL0093  Air India Express  ...                12970            2710730
132    FL0133             IndiGo  ...                15324            2513136
51     FL0052           SpiceJet  ...                13824            2253312
7      FL0008          Air India  ...                14173            2225161
176    FL0177            Vistara  ...                17306            2145944
36     FL0037            Vistara  ...                11614            2136976
108    FL0109           SpiceJet  ...                16390            2114310
107    FL0108             IndiGo  ...                10551            2089098
30     FL0031            Vistara  ...                 9962            2082058

[10 rows x 6 columns]

    Flight_ID            Airline     Origin Destination  Delay_Minutes
50     FL0051          Air India      Delhi      Mumbai          110.0
26     FL0027           SpiceJet  Bengaluru   Hyderabad          110.0
82     FL0083  Air India Express    Lucknow       Delhi          110.0
57     FL0058             IndiGo  Hyderabad     Kolkata          110.0
177    FL0178             IndiGo      Delhi      Mumbai          110.0
128    FL0129           SpiceJet    Lucknow       Delhi          110.0
169    FL0170             IndiGo     Mumbai     Kolkata          110.0
161    FL0162          Air India  Hyderabad     Kolkata          110.0
146    FL0147             IndiGo     Mumbai     Kolkata          110.0
21     FL0022            Vistara      Kochi       Delhi           75.0

## 8. Grouping and Aggregation – Airline Analysis

In [9]:
airline_analysis = (
    df.groupby("Airline")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Delay_Minutes=("Delay_Minutes", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean"),
          Estimated_Revenue=("Estimated_Revenue", "sum")
      )
      .sort_values("Estimated_Revenue", ascending=False)
)

display(airline_analysis)

                   Flights  Passengers  ...  Avg_Satisfaction  Estimated_Revenue
Airline                                 ...
Vistara                 37        4484  ...          3.378378           28689467
IndiGo                  32        4158  ...          3.343750           25709131
SpiceJet                32        3929  ...          3.531250           24195935
Air India Express       24        3027  ...          3.666667           23944164
Akasa Air               31        3427  ...          3.419355           18872059
Air India               24        3074  ...          3.750000           16232418

[6 rows x 5 columns]

## 9. Flight Status Analysis

In [10]:
status_analysis = (
    df.groupby("Flight_Status")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Delay_Minutes=("Delay_Minutes", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean")
      )
      .sort_values("Flights", ascending=False)
)

display(status_analysis)

               Flights  Passengers  Avg_Delay_Minutes  Avg_Satisfaction
Flight_Status
On Time            114       13890           3.464912          3.587719
Delayed             59        7314          50.000000          3.271186
Cancelled            7         895           5.000000          3.857143

## 10. Travel Class Analysis

In [11]:
class_analysis = (
    df.groupby("Travel_Class")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Ticket_Price=("Average_Ticket_Price", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean"),
          Estimated_Revenue=("Estimated_Revenue", "sum")
      )
      .sort_values("Estimated_Revenue", ascending=False)
)

display(class_analysis)

                 Flights  Passengers  ...  Avg_Satisfaction  Estimated_Revenue
Travel_Class                          ...
Economy              134       16054  ...          3.462687           73536524
Premium Economy       35        4574  ...          3.685714           39787685
Business              11        1471  ...          3.272727           24318965

[3 rows x 5 columns]

## 11. Weather Analysis

In [12]:
weather_analysis = (
    df.groupby("Weather")
      .agg(
          Flights=("Flight_ID", "count"),
          Avg_Delay_Minutes=("Delay_Minutes", "mean"),
          Delayed_Flights=("Flight_Status", lambda x: (x == "Delayed").sum()),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean")
      )
      .sort_values("Avg_Delay_Minutes", ascending=False)
)

display(weather_analysis)

         Flights  Avg_Delay_Minutes  Delayed_Flights  Avg_Satisfaction
Weather
Rain          43          21.418605               15          3.372093
Storm         30          19.600000               11          3.166667
Cloudy        38          18.842105               12          3.842105
Clear         34          18.029412               12          3.352941
Fog           35          15.485714                9          3.685714

## 12. Route Analysis

In [13]:
route_analysis = (
    df.groupby(["Origin", "Destination"])
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Delay_Minutes=("Delay_Minutes", "mean"),
          Estimated_Revenue=("Estimated_Revenue", "sum")
      )
      .sort_values("Estimated_Revenue", ascending=False)
)

display(route_analysis.head(10))

                       Flights  ...  Estimated_Revenue
Origin    Destination           ...
Delhi     Chennai           17  ...           15801818
Srinagar  Delhi             15  ...           14225022
Mumbai    Bengaluru         16  ...           12021596
Pune      Delhi             11  ...           10968185
Ahmedabad Bengaluru         12  ...           10635427
Delhi     Srinagar          13  ...           10364358
Mumbai    Kolkata           13  ...            9738285
Bengaluru Hyderabad         13  ...            8975058
Kochi     Delhi             14  ...            8438384
Delhi     Mumbai            13  ...            7330347

[10 rows x 4 columns]

## 13. Booking Channel Analysis

In [14]:
booking_analysis = (
    df.groupby("Booking_Channel")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Estimated_Revenue=("Estimated_Revenue", "sum"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean")
      )
      .sort_values("Estimated_Revenue", ascending=False)
)

display(booking_analysis)

                      Flights  Passengers  Estimated_Revenue  Avg_Satisfaction
Booking_Channel
Travel Agency              44        5542           35413370          3.386364
Online Travel Portal       50        6175           35238258          3.740000
Mobile App                 45        5226           34768242          3.444444
Airline Website            41        5156           32223304          3.365854

## 14. Monthly Analysis

In [15]:
monthly_analysis = (
    df.groupby(["Flight_Month", "Flight_Month_Name"])
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Estimated_Revenue=("Estimated_Revenue", "sum"),
          Avg_Delay_Minutes=("Delay_Minutes", "mean")
      )
      .sort_index()
)

display(monthly_analysis)

                                Flights  ...  Avg_Delay_Minutes
Flight_Month Flight_Month_Name           ...
1            January                 29  ...          22.103448
2            February                28  ...          22.750000
3            March                   33  ...          10.000000
4            April                   35  ...          24.828571
5            May                     30  ...          16.133333
6            June                    25  ...          16.760000

[6 rows x 4 columns]

## 15. Passenger Satisfaction Analysis

In [16]:
satisfaction_analysis = (
    df.groupby("Passenger_Satisfaction")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Delay_Minutes=("Delay_Minutes", "mean")
      )
      .sort_index()
)

display(satisfaction_analysis)

                        Flights  Passengers  Avg_Delay_Minutes
Passenger_Satisfaction
2                            50        5780          17.660000
3                            41        4577          20.951220
4                            39        5449          28.307692
5                            50        6293          10.680000

## 16. Key Findings and Observations

In [17]:
top_airline = airline_analysis["Estimated_Revenue"].idxmax()
top_airline_revenue = airline_analysis.loc[top_airline, "Estimated_Revenue"]

top_class = class_analysis["Estimated_Revenue"].idxmax()
top_class_revenue = class_analysis.loc[top_class, "Estimated_Revenue"]

worst_weather = weather_analysis["Avg_Delay_Minutes"].idxmax()
worst_weather_delay = weather_analysis.loc[worst_weather, "Avg_Delay_Minutes"]

top_route = route_analysis.index[0]
top_route_revenue = route_analysis.iloc[0]["Estimated_Revenue"]

top_booking = booking_analysis["Estimated_Revenue"].idxmax()
top_booking_revenue = booking_analysis.loc[top_booking, "Estimated_Revenue"]

print(f"1. The dataset contains {total_flights} flights carrying {total_passengers:,} passengers.")
print(f"2. The overall passenger load factor is {overall_load_factor:.2f}%, while estimated revenue is ₹{estimated_revenue:,.0f}.")
print(f"3. {top_airline} has the highest estimated revenue at ₹{top_airline_revenue:,.0f}.")
print(f"4. {top_class} generates the highest estimated revenue among travel classes at ₹{top_class_revenue:,.0f}.")
print(f"5. {delayed_rate:.2f}% of flights are delayed and {cancelled_rate:.2f}% are cancelled.")
print(f"6. {worst_weather} has the highest average delay at {worst_weather_delay:.2f} minutes.")
print(f"7. The highest-revenue route is {top_route[0]} → {top_route[1]}, generating about ₹{top_route_revenue:,.0f}.")
print(f"8. {top_booking} generates the highest estimated revenue among booking channels at ₹{top_booking_revenue:,.0f}.")

1. The dataset contains 180 flights carrying 22,099 passengers.
2. The overall passenger load factor is 62.25%, while estimated revenue is ₹137,643,174.
3. Vistara has the highest estimated revenue at ₹28,689,467.
4. Economy generates the highest estimated revenue among travel classes at ₹73,536,524.
5. 32.78% of flights are delayed and 3.89% are cancelled.
6. Rain has the highest average delay at 21.42 minutes.
7. The highest-revenue route is Delhi → Chennai, generating about ₹15,801,818.
8. Travel Agency generates the highest estimated revenue among booking channels at ₹35,413,370.

## 17. Export the Final Processed Dataset

In [18]:
output_file = "Day10_Final_Processed_Flight_Operations.csv"
df.to_csv(output_file, index=False)

print(f"Saved: {output_file}")
print("Final shape:", df.shape)

Saved: Day10_Final_Processed_Flight_Operations.csv
Final shape: (180, 22)

## Conclusion

The Flight Operations dataset was processed through the complete data-analysis workflow: ingestion, cleaning, transformation, analysis, and export. Pandas selection, filtering, sorting, grouping, aggregation, datetime operations, and derived columns were used to identify operational, revenue, route, weather, booking, and passenger-satisfaction patterns.