# Assignment: Dataset Summary Report (Day 7)

## Student Dataset Analysis using Python and Pandas

This notebook loads the provided student CSV dataset into a Pandas DataFrame and explores its basic structure and characteristics.

### Objectives
- Inspect the first and last few rows
- View random samples
- Check the dataset shape, columns, and index
- Examine data types and non-null values
- Generate descriptive statistics using `describe()`
- Identify missing values
- Record basic observations about the dataset

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("Day7_Student_Dataset.csv")

print("Dataset loaded successfully.")

Dataset loaded successfully.

## 1. First Few Rows

In [2]:
df.head()

   Student_ID          Name  Age  ... Marks  Attendance_Percentage      City
0        1001  Aarav Sharma   19  ...  87.0                   91.0  Srinagar
1        1002     Zoya Khan   20  ...  92.0                   95.0     Delhi
2        1003   Rohan Mehta   18  ...  76.0                   82.0    Mumbai
3        1004  Ananya Singh   21  ...  81.0                   88.0  Srinagar
4        1005     Kabir Ali   19  ...  69.0                   76.0   Lucknow

[5 rows x 7 columns]

## 2. Last Few Rows

In [3]:
df.tail()

    Student_ID          Name  Age  ... Marks  Attendance_Percentage       City
20        1021    Aman Kumar   18  ...  74.0                   78.0      Delhi
21        1022    Alina Shah   19  ...  96.0                   98.0   Srinagar
22        1023   Nikhil Sood   22  ...  78.0                   83.0       Pune
23        1024   Maryam Khan   20  ...  85.0                   88.0  Hyderabad
24        1025  Reyansh Jain   21  ...  80.0                   84.0    Kolkata

[5 rows x 7 columns]

## 3. Random Sample of Rows

In [4]:
df.sample(5, random_state=42)

    Student_ID          Name  Age  ... Marks  Attendance_Percentage       City
8         1009    Arjun Nair   18  ...  84.0                   86.0      Kochi
16        1017     Dev Patel   19  ...  86.0                   89.0  Ahmedabad
0         1001  Aarav Sharma   19  ...  87.0                   91.0   Srinagar
23        1024   Maryam Khan   20  ...  85.0                   88.0  Hyderabad
11        1012     Aisha Mir   19  ...  68.0                   72.0      Delhi

[5 rows x 7 columns]

## 4. Dataset Shape

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Shape:", df.shape)

Rows: 25
Columns: 7
Shape: (25, 7)

## 5. Column Names

In [6]:
print("Columns:")
print(df.columns.tolist())

Columns:
['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage', 'City']

## 6. Dataset Index

In [7]:
print(df.index)

RangeIndex(start=0, stop=25, step=1)

## 7. Dataset Information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

## 8. Data Types

In [9]:
print(df.dtypes)

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

## 9. Descriptive Statistics

In [10]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

## 10. Missing Values

In [11]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

Missing values in each column:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

Total missing values: 3

## 11. Basic Dataset Observations

In [12]:
print(f"1. The dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")
print(f"2. The dataset has {df.shape[1]} features: {', '.join(df.columns)}.")
print("3. Integer columns:", ", ".join(df.select_dtypes(include="int64").columns))
print("4. Floating-point columns:", ", ".join(df.select_dtypes(include="float64").columns))
print("5. Object/text columns:", ", ".join(df.select_dtypes(include="object").columns))

total_missing = int(df.isnull().sum().sum())
if total_missing == 0:
    print("6. No missing values were found in the dataset.")
else:
    print(f"6. The dataset contains {total_missing} missing value(s).")
    print("   Missing values by column:")
    print(df.isnull().sum()[df.isnull().sum() > 0])

1. The dataset contains 25 rows and 7 columns.
2. The dataset has 7 features: Student_ID, Name, Age, Course, Marks, Attendance_Percentage, City.
3. Integer columns: Student_ID, Age
4. Floating-point columns: Marks, Attendance_Percentage
5. Object/text columns: Name, Course, City
6. The dataset contains 3 missing value(s).
   Missing values by column:
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

## 12. Conclusion

The student dataset was successfully loaded and inspected using Pandas. The analysis covered the dataset's rows, columns, index, data types, structure, descriptive statistics, and missing values. These checks provide a basic understanding of the dataset before performing more advanced analysis.